import { Resource, StartupProfile } from '../types';

export const mockResources: Resource[] = [
  {
    id: '1',
    title: 'The Lean Startup Methodology',
    description: 'Learn how to build a successful startup using lean principles, rapid iteration, and validated learning. Perfect for early-stage founders.',
    content_type: 'Article',
    category: 'Business',
    tags: ['lean', 'methodology', 'mvp', 'validation'],
    industry_tags: ['Technology', 'SaaS'],
    stage_tags: ['Idea', 'Pre-seed', 'Seed'],
    difficulty_level: 'beginner',
    estimated_time: 15,
    url: 'https://example.com/lean-startup',
    thumbnail_url: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Eric Ries',
    published_at: new Date().toISOString(),
    view_count: 12453,
    rating_avg: 4.7,
    rating_count: 234,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '2',
    title: 'Pitch Deck Template for Series A',
    description: 'A comprehensive pitch deck template used by successful startups to raise Series A funding. Includes investor-ready slides.',
    content_type: 'Template',
    category: 'Fundraising',
    tags: ['pitch-deck', 'series-a', 'fundraising', 'investors'],
    industry_tags: ['Technology', 'SaaS', 'AI/ML'],
    stage_tags: ['Seed', 'Series A'],
    difficulty_level: 'intermediate',
    estimated_time: 30,
    url: 'https://example.com/pitch-deck',
    thumbnail_url: 'https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Y Combinator',
    published_at: new Date().toISOString(),
    view_count: 8932,
    rating_avg: 4.9,
    rating_count: 445,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '3',
    title: 'Growth Hacking Strategies for SaaS',
    description: 'Master growth hacking techniques specifically designed for SaaS products. Learn viral loops, referral programs, and retention tactics.',
    content_type: 'Course',
    category: 'Marketing',
    tags: ['growth-hacking', 'saas', 'marketing', 'retention'],
    industry_tags: ['SaaS', 'Technology'],
    stage_tags: ['Seed', 'Series A', 'Series B'],
    difficulty_level: 'advanced',
    estimated_time: 120,
    url: 'https://example.com/growth-hacking',
    thumbnail_url: 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Reforge',
    published_at: new Date().toISOString(),
    view_count: 15678,
    rating_avg: 4.8,
    rating_count: 567,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '4',
    title: 'Building Your First MVP in 30 Days',
    description: 'A practical guide to building and launching your minimum viable product quickly. Includes code examples and deployment strategies.',
    content_type: 'Video',
    category: 'Product',
    tags: ['mvp', 'product-development', 'launch', 'coding'],
    industry_tags: ['Technology', 'SaaS'],
    stage_tags: ['Idea', 'Pre-seed'],
    difficulty_level: 'intermediate',
    estimated_time: 45,
    url: 'https://example.com/mvp-video',
    thumbnail_url: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Product School',
    published_at: new Date().toISOString(),
    view_count: 9845,
    rating_avg: 4.6,
    rating_count: 312,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '5',
    title: 'Customer Discovery Interview Framework',
    description: 'Learn how to conduct effective customer discovery interviews to validate your product assumptions and find product-market fit.',
    content_type: 'Tool',
    category: 'Product',
    tags: ['customer-discovery', 'interviews', 'validation', 'product-market-fit'],
    industry_tags: ['Technology', 'E-commerce', 'SaaS'],
    stage_tags: ['Idea', 'Pre-seed', 'Seed'],
    difficulty_level: 'beginner',
    estimated_time: 20,
    url: 'https://example.com/customer-discovery',
    thumbnail_url: 'https://images.pexels.com/photos/3183172/pexels-photo-3183172.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'The Mom Test',
    published_at: new Date().toISOString(),
    view_count: 7234,
    rating_avg: 4.9,
    rating_count: 289,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: '6',
    title: 'Financial Modeling for Startups',
    description: 'Build comprehensive financial models for your startup. Includes templates for revenue projections, burn rate, and runway calculations.',
    content_type: 'Template',
    category: 'Business',
    tags: ['finance', 'modeling', 'projections', 'fundraising'],
    industry_tags: ['Technology', 'SaaS', 'Fintech'],
    stage_tags: ['Seed', 'Series A', 'Series B'],
    difficulty_level: 'intermediate',
    estimated_time: 60,
    url: 'https://example.com/financial-modeling',
    thumbnail_url: 'https://images.pexels.com/photos/6801648/pexels-photo-6801648.jpeg?auto=compress&cs=tinysrgb&w=800',
    author: 'Carta',
    published_at: new Date().toISOString(),
    view_count: 11234,
    rating_avg: 4.7,
    rating_count: 423,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export function generateMockProfile(userId: string): StartupProfile {
  return {
    id: 'profile-1',
    user_id: userId,
    company_name: '',
    industry: '',
    stage: '',
    team_size: 0,
    funding_raised: 0,
    location: '',
    founded_date: '',
    description: '',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };
}
